name: Update Fastly IPs

on:
  schedule:
    - cron: '45 2 * * *'
  workflow_dispatch:

jobs:
  update-ips:
    runs-on: ubuntu-slim
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Create directories
        run: mkdir -p subnets/v4 subnets/v6

      - name: Fetch and process IP ranges
        run: |
          # Скачиваем префиксы через RIPE Stat API
          curl --fail --silent --show-error -s "https://stat.ripe.net/data/announced-prefixes/data.json?resource=AS54113" -o as54113.json

          # Объединяем и разбиваем по версиям
          jq -r '.data.prefixes[].prefix' as54113.json \
            | grep -v ':' | sort -Vu > subnets/v4/fastly.lst

          python3 optimize_subnets.py subnets/v4/fastly.lst

          jq -r '.data.prefixes[].prefix' as54113.json \
            | grep ':' | sort -Vu > subnets/v6/fastly.lst

          python3 optimize_subnets.py subnets/v6/fastly.lst

          rm as54113.json

      - name: Check for changes and commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add subnets/

          if git diff --staged --quiet; then
            echo "Нет изменений в подсетях. Коммит отменен."
          else
            git commit -m "chore: update Fastly subnets [$(date +'%Y-%m-%d')]"
            git push
            echo "Изменения успешно закоммичены."
          fi
